{
  description = "Example West project consuming west-nix";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    # For this example, use the local west-nix
    # In production, use: west-nix.url = "github:JPHutchins/west-nix";
    west-nix.url = "path:../..";
  };

  outputs = { self, nixpkgs, west-nix }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      westLib = west-nix.lib.${system};

      # Import the lockfile generated by westupdate
      westProjects = westLib.mkWestProjects ./westlock.nix;

      # Create workspace setup script
      westinit = westLib.mkWestWorkspace {
        inherit westProjects;
      };
    in
    {
      packages.${system} = {
        # Expose the setup script for manual use
        inherit westinit;

        # Expose individual project derivations
        # Example: self.packages.${system}.zephyr
      } // builtins.listToAttrs (map (proj: {
        name = proj.name;
        value = proj.src;
      }) westProjects);

      # Development shell with West workspace pre-configured
      devShells.${system}.default = pkgs.mkShell {
        buildInputs = [
          # Your build tools here
          pkgs.cmake
          pkgs.ninja

          # Workspace setup script
          westinit
        ];

        shellHook = ''
          echo "West development environment"
          echo ""

          # Set up workspace in subdirectory (like node_modules, .venv, etc.)
          WORKSPACE_DIR="$PWD/.west-workspace"

          # Run workspace setup if not already set up
          if [ ! -L "$WORKSPACE_DIR/zephyr" ]; then
            echo "Setting up West workspace in ./.west-workspace..."
            westinit "$PWD" west.yml "$WORKSPACE_DIR"
          fi

          # Source the workspace environment
          if [ -f "$WORKSPACE_DIR/env.sh" ]; then
            source "$WORKSPACE_DIR/env.sh"
          fi

          echo ""
          echo "West workspace is ready at: ./.west-workspace"
          if [ -n "''${ZEPHYR_BASE:-}" ]; then
            echo "ZEPHYR_BASE=$ZEPHYR_BASE"
          fi
          echo ""
          echo "Run 'west list' to see all projects"
        '';
      };
    };
}
