# This file is auto-generated by west-to-nix
# DO NOT EDIT MANUALLY
[
  {
    name = "zephyr";
    path = "zephyr";
    url = "https://github.com/zephyrproject-rtos/zephyr";
    rev = "3cf7b202780d788976e4bf3e46724e63d23f6bcc";
    sha256 = "1z8p3i7149cls3snlsyr7l3i3cgscai6806n2ghgwplk0j1arysb";
  }
  {
    name = "cmsis_6";
    path = "modules/hal/cmsis_6";
    url = "https://github.com/zephyrproject-rtos/CMSIS_6";
    rev = "30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74";
    sha256 = "16nz1kqjknwv397hda20vjccaw23h5ka8k76kihfz9kl4chs2dwx";
  }
  {
    name = "hal_nordic";
    path = "modules/hal/nordic";
    url = "https://github.com/zephyrproject-rtos/hal_nordic";
    rev = "7858281d843468fe53c829995fb63f45a227387a";
    sha256 = "1cchgxy7p5lgys7z3ggv8g13d7kwl3f3fsqv3g0a9nrm9psmmw27";
  }
  {
    name = "hal_stm32";
    path = "modules/hal/stm32";
    url = "https://github.com/zephyrproject-rtos/hal_stm32";
    rev = "286dd285b5bb4fddafdfff27b5405264e5a61bfe";
    sha256 = "07v18xdjgizi0rh5cl0harbmm3l9myv8lq0rb885wkdz2p9yhps9";
  }
]
