"""Generate Nix expressions from West lockfile data."""

from typing import NamedTuple

from .prefetch import PrefetchResult
from .schema import WestProject


class NixProject(NamedTuple):
    """A West project with its Nix hash information."""

    project: WestProject
    sha256: str


def generate_nix_expression(projects: list[NixProject]) -> str:
    """Generate a Nix expression for a list of West projects.

    Args:
        projects: List of projects with their SHA256 hashes

    Returns:
        A Nix expression as a string containing the project list
    """
    lines = [
        "# This file is auto-generated by west-to-nix",
        "# DO NOT EDIT MANUALLY",
        "[",
    ]

    for proj in projects:
        p = proj.project
        lines.append("  {")
        lines.append(f'    name = "{p.name}";')
        lines.append(f'    path = "{p.nix_path}";')
        lines.append(f'    url = "{p.url}";')
        lines.append(f'    rev = "{p.revision}";')
        lines.append(f'    sha256 = "{proj.sha256}";')
        lines.append("  }")

    lines.append("]")

    return "\n".join(lines)


def escape_nix_string(s: str) -> str:
    """Escape a string for use in Nix expressions.

    Args:
        s: String to escape

    Returns:
        Escaped string safe for Nix
    """
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
